name: Calculator CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  unit-test:
    run-on: ubuntu-latest

    steps:
    - name: Checkout (Git pull)
      uses: actions/checkout@v4

    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install unittests

    - name: Run unittests
      run: |
        python unit.py